### ISSUE TITLE
Integration of environment variables

### ISSUE THREAD

**Issue by sergio-ridaura** [sergio-ridaura/node-start#12]
## Describe the feature

Integrating environment variables into your Node.js project.

**Comment by n-keerthi-gayathri** [comment]
@sergio-ridaura please assign me this

**Comment by sergio-ridaura** [comment]
@n-keerthi-gayathri Thanks for the comment, but you don't need to, this project is a refactoring of an old one.
When this finish I would appreciate feedback for an improvement or if you feel something is missing.
